Repository GardenOfWriter/garden-of-writer-backend, pull requests merged in 2023-06, with the labels that each got.

#2 template setting
  .COMMIT_TEMPLATE.txt
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/feature.md
  .github/issue-branch.yml
  .github/pull_request_template.md
  .github/workflows/create_branch_for_issue.yml
  README.md
  scripts/prepare-commit-msg.sh
Labels: doc

#7 env 관련 코드를 변경합니다.
  .infisical.json
  README.md
  package.json
  schema.gql
  src/apis/auth/auth.module.ts
  src/apis/auth/auth.resolver.ts
  src/apis/auth/auth.service.ts
  src/apis/mail/mail.module.ts
  src/apis/mail/mail.service.ts
  src/apis/user/user.module.ts
  src/app.module.ts
  src/commons/auth/jwt-access.strategy.ts
  src/commons/auth/jwt-refresh.strategy.ts
  src/commons/auth/jwt-social-google.strategy.ts
  src/commons/config/app-config/app-config.constant.ts
  src/commons/config/app-config/app-config.module.ts
  src/commons/config/app-config/app-config.service.spec.ts
  src/commons/config/app-config/app-config.service.ts
  src/commons/config/external-config/external-config.module.ts
  src/commons/config/external-config/external-config.service.spec.ts
  src/commons/config/external-config/external-config.service.ts
  yarn.lock
Labels: feat, modify, refactor, test, doc

#11 user decorator 를 생성합니다.
  src/commons/decorators/user.decorator.ts
Labels: feat

#13 database 타입을 변경합니다.
  package.json
  src/commons/config/app-config/app-config.constant.ts
  src/commons/config/app-config/app-config.module.ts
  src/commons/config/external-config/external-config.service.ts
  yarn.lock
Labels: modify

#16 filename을 변경합니다.
  src/apis/Image/dto/image.input.ts
  src/apis/Image/entities/image.entity.ts
  src/apis/Image/images.module.ts
  src/apis/Image/images.resolver.ts
  src/apis/Image/images.service.ts
  src/apis/attend-list/attend-list.module.ts
  src/apis/attend-list/attend-list.resolver.ts
  src/apis/attend-list/attend-list.service.ts
  src/apis/attend-list/dto/attend-list.output.ts
  src/apis/attend-list/entities/attend-list.entity.ts
  src/apis/auth/auth.module.ts
  src/apis/board/board.resolver.ts
  src/apis/board/dto/board-and-user.output.ts
  src/apis/board/dto/create-board.input.ts
  src/apis/board/dto/update-board.input.ts
  src/apis/comment/comment.service.ts
  src/apis/comment/entities/comment.entity.ts
  src/apis/fiction-board/dto/attend-list.output.ts
  src/apis/fiction-board/dto/create-board.input.ts
  src/apis/fiction-board/dto/fiction-board-and-user.output.ts
  src/apis/fiction-board/dto/update-board.input.ts
  src/apis/fiction-board/entities/fiction-board.entity.ts
  src/apis/fiction-board/fiction-board.module.ts
  src/apis/fiction-board/fiction-board.resolver.ts
  src/apis/fiction-board/fiction-board.service.ts
  src/apis/follow-counts/follow-count.entity.ts
  src/apis/follow/dto/follower-list.output.ts
  src/apis/follow/dto/following-list.output.ts
  src/apis/follow/follow.module.ts
  src/apis/follow/follow.service.ts
  src/apis/mail/mail.module.ts
  src/apis/nested-comment/entities/nested-comment.entity.ts
  src/apis/nested-comment/nested-comment.module.ts
  src/apis/nested-comment/nested-comment.resolver.ts
  src/apis/nested-comment/nested-comment.service.ts
  src/apis/pick/dto/picks-with-board.output.ts
  src/apis/pick/entities/pick.entity.ts
  src/apis/tag/entities/tag.entity.ts
  src/apis/user/entities/user.entity.ts
  src/apis/user/user.module.ts
  src/apis/user/user.service.ts
Labels: refactor

#18 filename을 재수정합니다.
  src/apis/comment/comment.module.ts
  src/apis/fiction-board/entities/fiction-board.entity.ts
  src/apis/follow/follow.resolver.ts
  src/apis/nested-comment/nested-comment.resolver.ts
  src/apis/pick/picks.module.ts
  src/apis/pick/picks.service.ts
  src/apis/user/user.module.ts
  src/app.module.ts
Labels: refactor

#23 create issue branch yml 수정
  .github/issue-branch.yml
Labels: modify

#26 user decorator 수정
  src/commons/decorators/user.decorator.ts
Labels: fix
